spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Diatonic_Academy
    driver-class-name: org.postgresql.Driver
    username: "Jose Miguel"
    password: "JMmf1996"

  jpa:
    hibernate:
      ddl-auto: validate   # cuidado: update modifica el esquema autom√°ticamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
